package com.bjfu.entity;

public class SalGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.GRADE
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.LOSAL
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    private Integer losal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salgrade.HISAL
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    private Integer hisal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.GRADE
     *
     * @return the value of salgrade.GRADE
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.GRADE
     *
     * @param grade the value for salgrade.GRADE
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.LOSAL
     *
     * @return the value of salgrade.LOSAL
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    public Integer getLosal() {
        return losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.LOSAL
     *
     * @param losal the value for salgrade.LOSAL
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    public void setLosal(Integer losal) {
        this.losal = losal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salgrade.HISAL
     *
     * @return the value of salgrade.HISAL
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    public Integer getHisal() {
        return hisal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salgrade.HISAL
     *
     * @param hisal the value for salgrade.HISAL
     *
     * @mbg.generated Tue Jan 05 11:23:47 CST 2021
     */
    public void setHisal(Integer hisal) {
        this.hisal = hisal;
    }
}